# theme: minima

title: Moments of Power
email: t.steffen@ieee.org
last_edit_timestamp: true 
mathjax: true

description: >
  Dedicated to the statistical analysis of energy systems. 
  
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%y'

